auto: true
server: true
permalink: /:categories/:title
baseurl: /egy-election-data
github: "http://github.com/mbaldassaro/egy-election-data"
languages:
  - name: 'English'
    key: 'en'
  - name: 'Arabic'
    key: 'ar'
